### ISSUE TITLE
Not working with GitHub Pages?

### ISSUE THREAD

**Issue by Raymai97** [samrayner/jekyll-asset-path-plugin#12]
Hi. I used your plugin in my Jekyll blog site. It works fine when I preview it in localhost, but when I publish the site to gh-pages, GitHub said:

> Your site is having problems building: The tag asset_path on line 44 in _posts/2017-05-03-enable-direct3d-in-win2k-vbox.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

Apparently it is mentioning this line `![img]({% asset_path true-kernel32-string.png %})  `. 

And when I read [this](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/), it said

> Other plugins are not supported, so the only way to incorporate them in your site is to generate your site locally and then push your site's static files to your GitHub Pages site.

I thought I already generated the site locally when I run `bundle exec jekyll serve`? I'm confused now.

**Comment by Raymai97** [comment]
Finally figured out by myself. 
This is what I was doing:
myblog <- `git init` here
|- _plugins
|- _site
|- _posts

The right way to publish a static site is like this:
myblog
|- _plugins
|- _site <- `git init` here
|- _posts

If your site URL is just `foobar.github.io`, then it should work out-of-the-box after `git add`, `git commit` and `git push`. If your site URL is something like `foobar.github.io/foo` you must specify it in `baseurl` in `_config.yml` as `/foo`.

**Comment by samrayner** [comment]
Glad you sorted it Raymai, thanks :)
