### ISSUE TITLE
Inconsistent asset path for _drafts

### ISSUE THREAD

**Issue by grant-h** [samrayner/jekyll-asset-path-plugin#3]
While using this plugin, I like to work with drafts and regular posts. This works great for all `.md` files in the `_posts` folder, but when running `jekyll serve --drafts` and viewing assets on draft posts, they appear to be at a different path. When the draft post is moved to the published posts folder the asset path is correct.

Not sure if this is feature or a bug.

**Comment by samrayner** [comment]
Hi Grant. Sorry about that. I'm afraid I don't use Jekyll any more but if you are able to submit a pull request I'd be happy to merge.
