### ISSUE TITLE
Make this a ruby gem

### ISSUE THREAD

**Issue by alias1** [samrayner/jekyll-asset-path-plugin#5]
It would be awesome to see this worked into a ruby gem.

Skeleton can be generated with `bundle gem jekyll-asset-path` ([more info](https://github.com/aarongustafson/jekyll-webmention_io/issues/3#issuecomment-186366850))

Then installation can be setup [like this](https://github.com/jekyll/jekyll-feed#installation)

**Comment by samrayner** [comment]
I understand the appeal but it seems a bit unnecessary when installation only involves copying one file at the moment. The plugin is also extremely simple and unlikely to see any updates really. Sorry! Feel free to fork and create a gem though.

**Comment by ahangarha** [comment]
Copy/pasting of code doesn't seem a good approach.

Still, there is no harm in making it a standard gem. One can still copy/paste the code.

If needed, I make a PR for it.
